# Generated by Django 2.2.1 on 2019-06-17 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=90)),
                ('team2', models.CharField(max_length=90)),
                ('toss_winner', models.CharField(default=None, max_length=90)),
                ('toss_decision', models.CharField(default=None, max_length=90)),
                ('result', models.CharField(default=None, max_length=90)),
                ('dl_applied', models.CharField(default=0, max_length=90)),
                ('winner', models.CharField(default=None, max_length=90)),
                ('win_by_run', models.IntegerField(default=0)),
                ('win_by_wickets', models.IntegerField(default=0)),
                ('player_of_match', models.CharField(max_length=90, null=True)),
                ('venue', models.CharField(max_length=90)),
                ('umpire1', models.CharField(max_length=90)),
                ('umpire2', models.CharField(max_length=90)),
                ('umpire3', models.CharField(default=None, max_length=90)),
            ],
        ),
    ]
