# Generated by Django 2.2.1 on 2019-06-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
