# Generated by Django 2.2.1 on 2019-06-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_auto_20190617_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
