# Generated by Django 2.2.1 on 2019-06-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0007_deliveries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
